name: High Speed Free RDP
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Setup RDP Connection Automatically
      uses: vishalvshekkar/remotely-easy@v1
      with:
        creds: ${{ secrets.NGROK_AUTH_TOKEN }}
