name: USA High Speed RDP
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Install Tailscale via Choco
      shell: powershell
      run: |
        choco install tailscale -y
    - name: Enable Windows Remote Desktop (RDP)
      shell: powershell
      run: |
        # RDP setting Registry mein enable karna
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        # Network Level Authentication (NLA) ko off karna taake bina password login ho sake
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0
        # RDP Firewall rules ko allow karna
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - name: Run Tailscale Service & Connect
      shell: powershell
      run: |
        Start-Service -Name "Tailscale" -ErrorAction SilentlyContinue
        & "C:\Program Files\Tailscale\tailscale.exe" up --authkey=tskey-auth-ku1TgFN39s11CNTRL-im2YdLucP3SbDvArAnsL3Sv9NoDJugXR
    - name: Keep RDP Alive
      shell: powershell
      run: |
        $seconds = 21600
        while ($seconds -gt 0) {
            Write-Output "RDP Active hai... Remaining: $seconds seconds"
            Start-Sleep -Seconds 60
            $seconds -= 60
        }
